name: zmq2mqtt pull request

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write 
    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
      
        - name: Update apt
          run: sudo apt-get update

        - name: Install dependencies
          run: sudo apt-get install -y libzmq3-dev

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.20'
            cache-dependency-path: go.sum
            
        - name: Pull eclipse-mosquito image that is required for tests
          run: docker pull eclipse-mosquitto
          
        # Install gotestfmt on the VM running the action.
        - name: Set up gotestfmt
          uses: gotesttools/gotestfmt-action@v2
          with:
            # Optional: pass GITHUB_TOKEN to avoid rate limiting.
            token: ${{ secrets.GITHUB_TOKEN }}
        
        - name: Test 
          run: |
            set -euo pipefail
            go test -json -v ./... 2>&1 -coverprofile=coverage.out | tee /tmp/zmq2mqtttest.log | gotestfmt

        - name: generate diff
          run: |
              git diff origin/${{ github.base_ref }}...origin/${{ github.head_ref }} > pr.diff
              
        - name: compute new code coverage
          id: covdiffaction
          uses: panagiotisptr/cov-diff@main
          with:
            path: .
            coverprofile: coverage.out
            diff: pr.diff
            module: github.com/panagiotisptr/cov-diff
    
        - name: Comment
          uses: mshick/add-pr-comment@v2
          with:
            message: |
              Coverage on new code: ${{ steps.covdiffaction.outputs.covdiff }}%
        
        # Upload the original go test log as an artifact for later review.
        - name: Upload test log
          uses: actions/upload-artifact@v2
          if: always()
          with:
            name: zmq2mqtttest-log
            path: /tmp/zmq2mqtttest.log
            if-no-files-found: error    
    
