name: zmq2mqtt core ci
  
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup libzmq
        run: sudo apt-get install libzmq3-dev

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: go.sum
    
      - name: Build
        run: go build -v ./...
        
      - name: Build docker
        run: docker build . -f docker/Dockerfile --tag zmq2mqtt
  test:
      needs: build
      runs-on: ubuntu-latest
      env:
          GOPATH: ${{ github.workspace }}
      defaults:
          run:
            working-directory: ${{ env.GOPATH }}/src/zmq2mqtt
            
      steps:    
        - uses: actions/checkout@v3
          with:
            path: ${{ env.GOPATH }}/src/zmq2mqtt
      
        - name: Setup libzmq
          run: sudo apt-get install libzmq3-dev

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.20'
            cache-dependency-path: go.sum
            
        - name: Pull eclipse-mosquito image that is required for tests
          run: docker pull eclipse-mosquitto
          
        # Install gotestfmt on the VM running the action.
        - name: Set up gotestfmt
          uses: gotesttools/gotestfmt-action@v2
          with:
            # Optional: pass GITHUB_TOKEN to avoid rate limiting.
            token: ${{ secrets.GITHUB_TOKEN }}
        
        - name: Test 
          run: |
            set -euo pipefail
            go test -json -v ./... 2>&1 | tee /tmp/zmq2mqtttest.log | gotestfmt
        
        # Upload the original go test log as an artifact for later review.
        - name: Upload test log
          uses: actions/upload-artifact@v2
          if: always()
          with:
            name: zmq2mqtttest-log
            path: /tmp/zmq2mqtttest.log
            if-no-files-found: error    
    
