name: zmq2mqtt core ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup libzmq
        run: sudo apt-get install libzmq3-dev

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: go.sum
    
      - name: Build
        run: go build -v ./...
        
      - name: Build docker
        run: docker build . -f docker/Dockerfile --tag zmq2mqtt
  test:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
      
        - name: Setup libzmq
          run: sudo apt-get install libzmq3-dev

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.20'
            cache-dependency-path: go.sum
        - name: Pull eclipse-mosquito image that is required for tests
          run: docker pull eclipse-mosquitto
          
        - name: Install test report HTML formatter
          run: go get -u github.com/vakenbolt/go-test-report/
        
        - name: Test 
          run: go test -json | go-test-report
        
        - name: Upload Go test results
          uses: actions/upload-artifact@v3
          with:
            name: test_report.html
            path: test_report.html     
    
